services:
  ubuntu-vnc:
    image: consol/ubuntu-xfce-vnc
    container_name: ubuntu-vnc-container
    restart: on-failure
    privileged: true
    user: root
    ports:
      - "5901:5901"
      - "6901:6901"
      - "2222:22"
    environment:
      - USER=root
      - PASSWORD=vncpassword
      - GEOMETRY=1280x800
      - DEPTH=24
      - HTTP_PORT=6901
    volumes:
      - ./setup_ssh.sh:/etc/cont-init.d/99-setup_ssh:ro 
      - ./data:/root
    shm_size: "512m"
#   Ejecutar desde la terminal: "/etc/cont-init.d/99-setup_ssh"



